### ISSUE TITLE
Unable to install dependency wxPython because QuickTime.h is deprecated 

### ISSUE THREAD

**Issue by noahbaxter** [hsnr-gamera/gamera#12] opened 2018-06-12 15:41 UTC
The Gamrea install instructions [here](http://gamera.informatik.hsnr.de/docs/gamera-docs/install.html) for osx 10.11 and above tells the user to build wxPython 3.0.2.0. However, the build process fails because QuickTime/QuickTime.h cannot be found, as this was deprecated in osx 10.9. How might one overcome this?

I am installing on High Sierra, osx 10.13.4

**Comment by cdalitz** [comment] 2018-06-13 16:32
According to the wxPython docs, QuickTime should not be used when the cocoa build is used.
Have you tried to build wxPython with the option "--osx_cocoa"?

**Comment by noahbaxter** [comment] 2018-06-13 18:11
Using the following command to build `python build-wxpython.py --build_dir=../bld --osx_cocoa --install`, I get the following errors.

```
/Users/noahbaxter/Projects/reqs/wxPython-src-3.0.2.0/src/osx/core/bitmap.cpp:39:10: fatal error: 'QuickTime/QuickTime.h' file not found
#include <QuickTime/QuickTime.h>
         ^~~~~~~~~~~~~~~~~~~~~~~
10 warnings and 1 error generated.
make: *** [monodll_core_bitmap.o] Error 1
make: *** Waiting for unfinished jobs....
10 warnings generated.
10 warnings generated.
10 warnings generated.
Error building
ERROR: failed building wxWidgets
Traceback (most recent call last):
  File "build-wxpython.py", line 389, in <module>
    wxbuild.main(wxscript, build_options)
  File "/Users/noahbaxter/Projects/reqs/wxPython-src-3.0.2.0/build/tools/build-wxwidgets.py", line 485, in main
    exitIfError(wxBuilder.build(dir=buildDir, options=args), "Error building")
  File "/Users/noahbaxter/Projects/reqs/wxPython-src-3.0.2.0/build/tools/build-wxwidgets.py", line 80, in exitIfError
    raise builder.BuildError(msg)
BuildError
```

I have xcode 9.4 and the current 10 beta installed on this machine

**Comment by cdalitz** [comment] 2018-06-15 05:51
I am using osx 10.13.4 and cannot reproduce your error. I have compiled wxpython with the following command:
`export CPPFLAGS=-D__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES=1
python build-wxpython.py --build_dir=../bld --osx_cocoa 
`

**Comment by cdalitz** [comment] 2019-02-12 10:09
@noahbaxter : We have now made Gamera compatible with wxPython 4.x. Can you please check whether this solves your install problem? Installation should now work out of the box with the combination python 2.7 & wxPython 4.0.

**Comment by vigliensoni** [comment] 2019-02-12 16:51
Hi Christoph,

Noah is not working with us anymore, but I can confirm that I was able to
install Gamera with pip version of wxPython (4.0.4) in macOS (10.13.6)

Thank you!

**Comment by cdalitz** [comment] 2019-02-13 08:56
@vigliensoni Thanks for testing this! I now close the issue.

**Closed by cdalitz** 2019-02-13 08:56 UTC
