### ISSUE TITLE
installation with pip requires wx, even with --nowx flag

### ISSUE THREAD

**Issue by noahbaxter** [hsnr-gamera/gamera#11] opened 2018-05-15 13:44 UTC
When attempting to install gamera with the following command

pip install git+https://github.com/hsnr-gamera/gamera.git --global-option="--nowx"

The instalation fails with the following output:

Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-req-build-9bFOuV/setup.py", line 235, in <module>
        import wx
    ImportError: No module named wx
Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-req-build-9bFOuV/

**Comment by cdalitz** [comment] 2018-05-16 07:15
The install option "-nowx" was introduced in Gamera version 3.4.1, but the version provided on PiPy is 3.3.3, so this option cannot work.

Please contact the person maintaining the PiPy entry to update to the latest Gamera release 3.4.3, or, preferably, to the latest git version. Please let us know, when the issue is fixed on PiPy.
Thanks for noticing this.

**Comment by vigliensoni** [comment] 2018-05-25 13:38
@noahbaxter Could you please check and report if you are now able to install Gamera with wxPython?

**Comment by noahbaxter** [comment] 2018-05-25 20:48
Yes, using the new instructions for osx 10.11+, I am able to install and access wxPython and Gamera from python. However, I am unable to use the gamera_gui as there is no access to the display. Even with the script provided in the install instructions, I still get the following error 

/Users/noahbaxter/bin/gamera_gui: line 35: /Frameworks/Python.framework/Versions/2.7/bin/python2.7: No such file or directory
/Users/noahbaxter/bin/gamera_gui: line 35: exec: /Frameworks/Python.framework/Versions/2.7/bin/python2.7: cannot execute: No such file or directory

Here are the states of the variables accessed by this line:
$FRAMEWORK_PYTHON = /Frameworks/Python.framework/Versions/2.7/bin/python2.7
$VIRTUAL_ENV = /usr/local/lib/py2wx3
$WXPYTHON_APP = gamera_gui

**Comment by noahbaxter** [comment] 2018-05-28 13:49
`/usr/local`

**Comment by cdalitz** [comment] 2018-05-28 13:55
> /usr/local
Then you must have overwritten $BREW_PYTHON_ROOT in your script. The prefix of $FRAMEWORK_PYTHON must start with "/usr/local" and cannot be  "/Frameworks" as you wrote in your previous comment.

**Comment by noahbaxter** [comment] 2018-05-29 17:54
After some troubleshooting, I was able to fix the issue by changing line 21 of the script to 
```
BREW_PYTHON_ROOT="`ls -d $(brew --prefix)/Cellar/python@2/$PYSUBVER*`"
```
. Brew may install python2 to python@2 sometimes so maybe this should be added to the documentation. Other than this, everything works fine now. Thanks

**Comment by cdalitz** [comment] 2018-06-06 06:47
> Brew may install python2 to python@2 sometimes so maybe this should be added to the documentation.

Just checked this on my system, and there are *two* python2 versions: both Cellar/python and Cellar/python@2. I have therefore merged your change of the respective script line into the documentation.
Thanks for noticing this.

**Closed by cdalitz** 2018-06-06 06:47 UTC
