### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by bwbohl** [hsnr-gamera/gamera#6] opened 2017-01-16 12:14 UTC
I tried to install gamera 3.4.2 from the release page on macOS Sierra 10.12.2 following the instructions in the `INSTALL` file, i.e. running:

`sudo python setup.py install`

Unfortunately the process fails on line 235 import wx with `ImportError: No module named wx`

The installed python version is 2.7.10, the one that came with the OS.

**Comment by ahankinson** [comment] 2017-01-16 20:13
DId you install wxWidgets?

**Comment by bwbohl** [comment] 2017-01-17 06:33
Ok, mixed that up with pythonw…
Nevertheless macOS won't let me install wxWidgets…
Probably I'll try to build it myself and report when done

**Comment by bwbohl** [comment] 2017-01-20 08:08
I finally managed to build and install wxWidgets from https://github.com/wxWidgets/wxWidgets/tree/v3.1.0

The installation should have been successfull, as the commandline returns:

```
wx-config --version
3.1.1
```

nevertheless in my gamera directory I get the above error on `python setup.py build`or `python setup.py`

What am I doing wrong?

**Comment by ahankinson** [comment] 2017-01-20 10:28
wxWidgets is a pain.

If you open your python prompt and do an `import wx` does it work? If not you will need to fix that first before trying to install gamera.

**Comment by bwbohl** [comment] 2017-01-20 10:30
Unfrotunately it doesn’t work…
I got no idea of how to fix this since I’m an absolute python-noob :-/

**Comment by ahankinson** [comment] 2017-01-20 11:16
what version of python are you using? if you do `which python` at a prompt what does it tell you?

**Comment by bwbohl** [comment] 2017-01-20 14:24
/usr/bin/python

version 2.7.10

**Comment by bwbohl** [comment] 2017-03-21 08:03
after installing python via brew (as recommended [here](https://github.com/Homebrew/legacy-homebrew/issues/30844)) wxmac is finally available for the build process, yet I stumble into the new problems:
``` python
include/rle_data.hpp:623:42: error: call to 'prev' is ambiguous
            typename list_type::iterator last = prev(m_data[chunk].end());
[…]

include/rle_data.hpp:681:44: error: call to 'prev' is ambiguous
            typename list_type::iterator prev_i = prev(i);
[…]

include/rle_data.hpp:719:44: error: call to 'next' is ambiguous
            typename list_type::iterator next_i = next(i);
[…]

include/rle_data.hpp:730:42: error: call to 'next' is ambiguous
          typename list_type::iterator next_i = next(i);
```

resulting in
```
4 errors generated.
error: command 'clang' failed with exit status 1
```

Any ideas how I can fix this?

**Comment by cdalitz** [comment] 2017-03-22 07:26
```
include/rle_data.hpp:623:42: error: call to 'prev' is ambiguous
            typename list_type::iterator last = prev(m_data[chunk].end())

```
This error should be fixed in the latest Gamera release. Have you used the latest Gamera source code?

**Comment by bwbohl** [comment] 2017-03-23 10:59
thanks for pushing my nose onto this… as I had started out with gamera before your most recent release I will retry with the new code and report afterwards!

**Comment by bwbohl** [comment] 2017-03-23 11:04
just downloaded gamera-4.3.4.tar.gz unpacked and ran:

```terminal
cd ./gamera-3.4.3
python setup.py build
```

unfortunately the result stays the same only the line references have changed. Am I missing something? Maybe some third-party library or the like?

**Comment by cdalitz** [comment] 2017-03-23 11:07
Can you please post the error report? Thanks.

**Comment by bwbohl** [comment] 2017-03-23 11:08
```terminal
4 errors generated.
error: command 'clang' failed with exit status 1
```

**Comment by cdalitz** [comment] 2017-03-23 12:11
Sorry, I did not mean the last two lines, but the message which source code lines produce the error.

**Comment by bwbohl** [comment] 2017-03-23 13:26
```terminal
In file included from include/gamera.hpp:62:
include/rle_data.hpp:628:42: error: call to 'prev' is ambiguous
            typename list_type::iterator last = std::prev(m_data[chunk].end());
                                                ^~~~~~~~~
include/rle_data.hpp:428:9: note: in instantiation of member function 'Gamera::RleDataDetail::RleVector<unsigned short>::set'
      requested here
        m_vec->set(m_pos, v, m_i);
               ^
include/accessor.hpp:55:9: note: in instantiation of member function
      'Gamera::RleDataDetail::RleVectorIteratorBase<Gamera::RleDataDetail::RleVector<unsigned short>,
      Gamera::RleDataDetail::RleVectorIterator<Gamera::RleDataDetail::RleVector<unsigned short> >,
      std::__1::__list_iterator<Gamera::RleDataDetail::Run<unsigned short>, void *> >::set' requested here
      i.set(v);
        ^
include/image_view.hpp:299:18: note: in instantiation of function template specialization 'Gamera::ImageAccessor<unsigned
      short>::set<Gamera::RleDataDetail::RleVectorIterator<Gamera::RleDataDetail::RleVector<unsigned short> > >' requested
      here
      m_accessor.set(value, m_begin + (p.y() * m_image_data->stride()) + p.x());
                 ^
src/imageobject.cpp:834:36: note: in instantiation of member function 'Gamera::ImageView<Gamera::RleImageData<unsigned short>
      >::set' requested here
    ((OneBitRleImageView*)o->m_x)->set(point,
                                   ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/iterator:530:1: note: 
      candidate function [with _BidiretionalIter = std::__1::__list_iterator<Gamera::RleDataDetail::Run<unsigned short>, void
      *>]
prev(_BidiretionalIter __x,
^
include/rle_data.hpp:58:5: note: candidate function [with T = std::__1::__list_iterator<Gamera::RleDataDetail::Run<unsigned
      short>, void *>]
  T prev(T i) {
    ^
include/rle_data.hpp:686:44: error: call to 'prev' is ambiguous
            typename list_type::iterator prev_i = std::prev(i);
                                                  ^~~~~~~~~
include/rle_data.hpp:625:6: note: in instantiation of member function 'Gamera::RleDataDetail::RleVector<unsigned
      short>::insert_in_run' requested here
            insert_in_run(pos, v, i);
            ^
include/rle_data.hpp:428:9: note: in instantiation of member function 'Gamera::RleDataDetail::RleVector<unsigned short>::set'
      requested here
        m_vec->set(m_pos, v, m_i);
               ^
include/accessor.hpp:55:9: note: in instantiation of member function
      'Gamera::RleDataDetail::RleVectorIteratorBase<Gamera::RleDataDetail::RleVector<unsigned short>,
      Gamera::RleDataDetail::RleVectorIterator<Gamera::RleDataDetail::RleVector<unsigned short> >,
      std::__1::__list_iterator<Gamera::RleDataDetail::Run<unsigned short>, void *> >::set' requested here
      i.set(v);
        ^
include/image_view.hpp:299:18: note: in instantiation of function template specialization 'Gamera::ImageAccessor<unsigned
      short>::set<Gamera::RleDataDetail::RleVectorIterator<Gamera::RleDataDetail::RleVector<unsigned short> > >' requested
      here
      m_accessor.set(value, m_begin + (p.y() * m_image_data->stride()) + p.x());
                 ^
src/imageobject.cpp:834:36: note: in instantiation of member function 'Gamera::ImageView<Gamera::RleImageData<unsigned short>
      >::set' requested here
    ((OneBitRleImageView*)o->m_x)->set(point,
                                   ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/iterator:530:1: note: 
      candidate function [with _BidiretionalIter = std::__1::__list_iterator<Gamera::RleDataDetail::Run<unsigned short>, void
      *>]
prev(_BidiretionalIter __x,
^
include/rle_data.hpp:58:5: note: candidate function [with T = std::__1::__list_iterator<Gamera::RleDataDetail::Run<unsigned
      short>, void *>]
  T prev(T i) {
    ^
include/rle_data.hpp:724:44: error: call to 'next' is ambiguous
            typename list_type::iterator next_i = std::next(i);
                                                  ^~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/iterator:519:1: note: 
      candidate function [with _ForwardIter = std::__1::__list_iterator<Gamera::RleDataDetail::Run<unsigned short>, void *>]
next(_ForwardIter __x,
^
include/rle_data.hpp:54:5: note: candidate function [with T = std::__1::__list_iterator<Gamera::RleDataDetail::Run<unsigned
      short>, void *>]
  T next(T i) {
    ^
include/rle_data.hpp:735:42: error: call to 'next' is ambiguous
          typename list_type::iterator next_i = std::next(i);
                                                ^~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/iterator:519:1: note: 
      candidate function [with _ForwardIter = std::__1::__list_iterator<Gamera::RleDataDetail::Run<unsigned short>, void *>]
next(_ForwardIter __x,
^
include/rle_data.hpp:54:5: note: candidate function [with T = std::__1::__list_iterator<Gamera::RleDataDetail::Run<unsigned
      short>, void *>]
  T next(T i) {
    ^
```

**Comment by cdalitz** [comment] 2017-03-23 18:26
The origin of the problem is, that std::prev and std::next were introduced into C++ in 2011. Therefore, these templates are defined in include/rle_data.hpp only for older C++ versions:
`#if __cplusplus < 201103
/*
  These are convenience functions to make dealing
  with the list iterators a little easier.
*/
namespace std {
  template<class T>
  T next(T i) {
    return ++i;
  }
  template<class T>
  T prev(T i) {
    return --i;
  }
}
#endif`
Is it possible to find out what your version of C++ is and how the macro "__cplusplus" is defined? Moreover, do you compile with the flag "-stdlib=libstdc++", which is necessary on OSX, I think?

**Comment by cdalitz** [comment] 2017-03-24 11:42
Apparently, the C++ version cannot be determined reliably with teh macro __cplusplus, because gcc had set this macro for a long time, a bug that was fixed not before 2011:
[(https://gcc.gnu.org/bugzilla/show_bug.cgi?id=1773)]

I have therefore defined the implementations of prev() and std() in a new namespace "std11" and used these functions in rle_data.hpp. Please let me know whether this fixes your problem, and, if yes, please close the issue. Thanks.

**Comment by bwbohl** [comment] 2017-03-24 20:01
sorry for having overseen to set

```terminal
export CFLAGS="-stdlib=libstdc++ -mmacosx-version-min=10.6"
```

in the build documentation on http://gamera.informatik.hsnr.de/docs/gamera-docs/install.html#mac-os-x

build process runs fine now except for a couple of warnings that

```terminal
clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9
```

haven't yet tested with libc++ though.

**Comment by bwbohl** [comment] 2017-03-24 20:01
thanks!

**Comment by bwbohl** [comment] 2017-03-24 20:13
installed successfully and running can switch to testing the application now ;-)

**Closed** 2017-03-26 08:59 UTC
